# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://aadityasg.github.io/
baseurl: /
title: Aaditya Gavandalkar
author: Aaditya Gavandalkar
description: Personal blog And Resume
avatar: profile.png
email: gavandalkar.1@osu.edu
github: aadityasg
twitter: 
linkedin: aaditya-gavandalkar-980a8036
stackoverflow: users/1791492/aaditya-gavandalkar
#Comment out if you don't want disqus 
disqus: aadityagavandalkar
google_analytics: UA-71770943-1


# needed for travis-ci build
exclude: [vendor]
